docker run
    -p 3306:3306
    --name spring-toby
    -e MYSQL_ROOT_PASSWORD=1
    -e MYSQL_DATABASE=springtoby
    -e MYSQL_USER=sunlee
    -e MYSQL_PASSWORD=pass
    -d mysql


docker run -p 3306:3306 --name spring-toby -e MYSQL_ROOT_PASSWORD=1 -e MYSQL_DATABASE=springtoby -e MYSQL_USER=sunlee -e MYSQL_PASSWORD=pass -d mysql

